ALTER TABLE [dbo].[FootballBets] DROP CONSTRAINT [FK_FootballBets_Group_groupId];
ALTER TABLE [dbo].[FootballBets] DROP CONSTRAINT [FK_FootballBets_MatchDays_matchdayId];
ALTER TABLE [dbo].[FootballBets] DROP CONSTRAINT [FK_FootballBets_TypePay_typePayid];
ALTER TABLE [dbo].[FootballBets] DROP CONSTRAINT [FK_FootballBets_TypeFootballBet_typeid];
ALTER TABLE [dbo].[MatchDays] DROP CONSTRAINT [FK_MatchDays_Teams_AwayTeamId];
ALTER TABLE [dbo].[MatchDays] DROP CONSTRAINT [FK_MatchDays_Competitions_CompetitionId];
ALTER TABLE [dbo].[MatchDays] DROP CONSTRAINT [FK_MatchDays_Teams_HomeTeamId];
ALTER TABLE [dbo].[ShopOffers] DROP CONSTRAINT [FK_ShopOffers_OfferTypes_typeid];
ALTER TABLE [dbo].[User] DROP CONSTRAINT [FK_User_Role_roleid];
ALTER TABLE [dbo].[UserFootballBet] DROP CONSTRAINT [FK_UserFootballBet_FootballBets_FootballBetId];
ALTER TABLE [dbo].[UserFootballBet] DROP CONSTRAINT [FK_UserFootballBet_User_userId];
ALTER TABLE [dbo].[UserGroup] DROP CONSTRAINT [FK_UserGroup_Role_blockedByid];
ALTER TABLE [dbo].[UserGroup] DROP CONSTRAINT [FK_UserGroup_Group_groupId];
ALTER TABLE [dbo].[UserGroup] DROP CONSTRAINT [FK_UserGroup_Role_roleid];
ALTER TABLE [dbo].[UserGroup] DROP CONSTRAINT [FK_UserGroup_User_userId];
ALTER TABLE [dbo].[UserToken] DROP CONSTRAINT [FK_UserToken_User_userId];
DROP TABLE [dbo].[__EFMigrationsHistory];
DROP TABLE [dbo].[Competitions];
DROP TABLE [dbo].[FootballBets];
DROP TABLE [dbo].[Group];
DROP TABLE [dbo].[MatchDays];
DROP TABLE [dbo].[OfferTypes];
DROP TABLE [dbo].[Role];
DROP TABLE [dbo].[ShopOffers];
DROP TABLE [dbo].[Teams];
DROP TABLE [dbo].[TypeFootballBet];
DROP TABLE [dbo].[TypePay];
DROP TABLE [dbo].[User];
DROP TABLE [dbo].[UserFootballBet];
DROP TABLE [dbo].[UserGroup];
DROP TABLE [dbo].[UserToken];